/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const DbDbIdIndexLazyImport = createFileRoute('/db/$dbId/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DbDbIdIndexLazyRoute = DbDbIdIndexLazyImport.update({
  path: '/db/$dbId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/db_.$dbId.index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/db/$dbId/': {
      id: '/db/$dbId/'
      path: '/db/$dbId'
      fullPath: '/db/$dbId'
      preLoaderRoute: typeof DbDbIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/db/$dbId': typeof DbDbIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/db/$dbId': typeof DbDbIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/db/$dbId/': typeof DbDbIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/db/$dbId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/db/$dbId'
  id: '__root__' | '/' | '/db/$dbId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DbDbIdIndexLazyRoute: typeof DbDbIdIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DbDbIdIndexLazyRoute: DbDbIdIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/db/$dbId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/db/$dbId/": {
      "filePath": "db_.$dbId.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
