/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DbDbIdIndexImport } from './routes/db_.$dbId.index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DbDbIdIndexRoute = DbDbIdIndexImport.update({
  path: '/db/$dbId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/db/$dbId/': {
      id: '/db/$dbId/'
      path: '/db/$dbId'
      fullPath: '/db/$dbId'
      preLoaderRoute: typeof DbDbIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/db/$dbId': typeof DbDbIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/db/$dbId': typeof DbDbIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/db/$dbId/': typeof DbDbIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/db/$dbId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/db/$dbId'
  id: '__root__' | '/' | '/db/$dbId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DbDbIdIndexRoute: typeof DbDbIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DbDbIdIndexRoute: DbDbIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/db/$dbId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/db/$dbId/": {
      "filePath": "db_.$dbId.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
